[package]
name = "wallet-types"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common/" }
crypto = { path = "../../crypto/" }
tx-verifier = { path = "../../chainstate/tx-verifier" }
rpc-description = { path = "../../rpc/description" }
randomness = { path = "../../randomness" }
serialization = { path = "../../serialization" }
storage = { path = "../../storage" }
utils = { path = "../../utils" }

bip39 = { workspace = true, default-features = false, features = ["std", "zeroize"] }
hex.workspace = true
itertools.workspace = true
parity-scale-codec.workspace = true
serde.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
test-utils = { path = "../../test-utils" }

rstest.workspace = true

[features]
trezor = []
default = ["trezor"]
