[package]
name = "wallet-rpc-daemon"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true
authors = ["Samer Afach <samer.afach@mintlayer.org>", "Ben Marsh <benjamin.marsh@mintlayer.org>", "Enrico Rubboli <enrico.rubboli@mintlayer.org>"]

[dependencies]

common = { path = "../../common" }
logging = { path = "../../logging" }
rpc = { path = "../../rpc" }
utils = { path = "../../utils" }
wallet-rpc-lib = { path = "../wallet-rpc-lib" }

clap.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]

rpc-description = { path = "../../rpc/description" }

expect-test.workspace = true

[features]
trezor = ["wallet-rpc-lib/trezor"]
default = ["trezor"]
