# Build Stage
FROM rust AS builder

WORKDIR /usr/src/wallet-gui

COPY . .

RUN cargo build --release -j1

# Runtime Stage
FROM debian:latest

# Install any necessary dependencies for your GUI (such as X11, GTK, etc.)
# Replace libgtk-3-0 with the appropriate dependencies for your application
RUN apt-get update && apt-get install -y ca-certificates libgtk-3-0 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/wallet-gui/target/release/wallet-gui /usr/bin/wallet-gui

CMD ["wallet-gui"]
