# Build Stage
FROM rust AS builder

WORKDIR /usr/src/node-daemon

COPY . .

RUN cargo build --release -j1

# Runtime Stage
FROM debian:latest

COPY --from=builder /usr/src/node-daemon/target/release/node-daemon /usr/bin/node-daemon

# Node daemon listens on ports 3030 and 13031
EXPOSE 3030 13031

# Define mintlayer directory as a volume
VOLUME ["/root/.mintlayer"]

CMD ["node-daemon"]
