# Dockerfile.wallet-cli

# Start from a minimal image with rust installed
FROM rust:1.54.0-alpine as build

# Create a new empty shell project
WORKDIR /usr/src
RUN USER=root cargo new wallet-cli
WORKDIR /usr/src/wallet-cli

# Build for release
RUN cargo build --release

# Our production image starts here
FROM alpine:latest

# Copy the binary from the build stage
COPY --from=build /usr/src/wallet-cli/target/release/wallet-cli .

# Run the binary
CMD ["./wallet-cli"]

