# Dockerfile.node-daemon
# Build Stage
FROM rust AS builder

WORKDIR /usr/src/node-daemon

COPY . .

RUN cargo build --release

# Runtime Stage
FROM debian:latest

COPY --from=builder /usr/src/node-daemon/target/release/node-daemon /usr/bin/node-daemon

CMD ["node-daemon"]
