max_width = 100
hard_tabs = false
tab_spaces = 4
array_width = 80
chain_width = 80
use_small_heuristics = "Max"
single_line_if_else_max_width = 50
newline_style = "Unix"
edition = "2021"

match_arm_leading_pipes = "Preserve"
