[package]
name = "p2p-backend-test-suite"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chainstate = { path = "../../chainstate/" }
common = { path = "../../common" }
crypto = { path = "../../crypto" }
logging = { path = "../../logging" }
p2p = { path = "../../p2p" }
p2p-test-utils = { path = "../p2p-test-utils" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem/" }
utils = { path = "../../utils/" }

futures.workspace = true
libtest-mimic.workspace = true
rlimit.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
