[package]
name = "node-comm"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockprod = { path = "../../blockprod" }
chainstate = { path = "../../chainstate" }
common = { path = "../../common" }
consensus = { path = "../../consensus" }
crypto = { path = "../../crypto" }
logging = { path = "../../logging" }
mempool = { path = "../../mempool" }
node-lib = { path = "../../node-lib" }
p2p = { path = "../../p2p" }
rpc = { path = "../../rpc" }
serialization = { path = "../../serialization" }
subsystem = { path = "../../subsystem" }
utils-networking = { path = "../../utils/networking" }
wallet-types = { path = "../types" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
mockall.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
tower.workspace = true

[dev-dependencies]
chainstate-storage = { path = "../../chainstate/storage" }

[features]
trezor = ["wallet-types/trezor"]
default = ["trezor"]
