# Build Stage
FROM rust AS builder

WORKDIR /usr/src/

COPY . .

ARG NUM_JOBS=1
RUN cargo build --release -j${NUM_JOBS}

# Runtime Stage
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/target/release/wallet-cli /usr/bin/wallet-cli

CMD ["wallet-cli"]

 