# Build Stage
FROM rust AS builder

WORKDIR /usr/src/

COPY . .

ARG NUM_JOBS=1
RUN cargo build --release -j${NUM_JOBS}

# Runtime Stage
FROM debian:bookworm-slim

COPY --from=builder /usr/src/target/release/node-daemon /usr/bin

# Node daemon listens on ports 3030 and 13031
EXPOSE 3030 13031

# Define mintlayer directory as a volume
VOLUME ["/root/.mintlayer"]

CMD ["node-daemon"]
