# Build Stage
FROM rust AS builder

WORKDIR /usr/src/wallet-cli

COPY . .

RUN cargo build --release -j1

# Runtime Stage
FROM debian:latest

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/wallet-cli/target/release/wallet-cli /usr/bin/wallet-cli

CMD ["wallet-cli"]
