[package]
name = "test-rpc-functions"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate-types = { path = "../chainstate/types" }
chainstate = { path = "../chainstate/" }
common = { path = "../common/" }
crypto = { path = "../crypto/" }
randomness = { path = "../randomness/" }
rpc = { path = "../rpc/" }
serialization = { path = "../serialization" }
subsystem = { path = "../subsystem/" }

async-trait.workspace = true
futures.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["macros"] }
parity-scale-codec.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
