[package]
name = "wallet-address-generator-lib"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../common" }
utils = { path = "../../utils" }
wallet-controller = { path = "../wallet-controller" }
wallet-types = { path = "../types" }
wallet = { path = "../../wallet" }
crypto = { path = "../../crypto" }

clap = { workspace = true, features = ["derive"] }

thiserror.workspace = true
