version: "3.8"

services:
  node01:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node01
    volumes:
      - data01:$DATA_DIR_IN_CONTAINER
    ports:
      - '40001:$RPC_PORT'
    # node01 is the "special" node that starts without peers; other containers depend on node01,
    # so it will be started earlier than any other node.
    command: node-daemon testnet $COMMON_NODE_ARGS

  node02:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node02
    volumes:
      - data02:$DATA_DIR_IN_CONTAINER
    ports:
      - '40002:$RPC_PORT'
    depends_on:
      - node01

  node03:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node03
    volumes:
      - data03:$DATA_DIR_IN_CONTAINER
    ports:
      - '40003:$RPC_PORT'
    depends_on:
      - node01

  node04:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node04
    volumes:
      - data04:$DATA_DIR_IN_CONTAINER
    ports:
      - '40004:$RPC_PORT'
    depends_on:
      - node01

  node05:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node05
    volumes:
      - data05:$DATA_DIR_IN_CONTAINER
    ports:
      - '40005:$RPC_PORT'
    depends_on:
      - node01

  node06:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node06
    volumes:
      - data06:$DATA_DIR_IN_CONTAINER
    ports:
      - '40006:$RPC_PORT'
    depends_on:
      - node01

  node07:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node07
    volumes:
      - data07:$DATA_DIR_IN_CONTAINER
    ports:
      - '40007:$RPC_PORT'
    depends_on:
      - node01

  node08:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node08
    volumes:
      - data08:$DATA_DIR_IN_CONTAINER
    ports:
      - '40008:$RPC_PORT'
    depends_on:
      - node01

  node09:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node09
    volumes:
      - data09:$DATA_DIR_IN_CONTAINER
    ports:
      - '40009:$RPC_PORT'
    depends_on:
      - node01

  node10:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node10
    volumes:
      - data10:$DATA_DIR_IN_CONTAINER
    ports:
      - '40010:$RPC_PORT'
    depends_on:
      - node01

  node11:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node11
    volumes:
      - data11:$DATA_DIR_IN_CONTAINER
    ports:
      - '40011:$RPC_PORT'
    depends_on:
      - node01

  node12:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node12
    volumes:
      - data12:$DATA_DIR_IN_CONTAINER
    ports:
      - '40012:$RPC_PORT'
    depends_on:
      - node01

  node13:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node13
    volumes:
      - data13:$DATA_DIR_IN_CONTAINER
    ports:
      - '40013:$RPC_PORT'
    depends_on:
      - node01

  node14:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node14
    volumes:
      - data14:$DATA_DIR_IN_CONTAINER
    ports:
      - '40014:$RPC_PORT'
    depends_on:
      - node01

  node15:
    extends:
      file: docker-compose-base.yml
      service: node
    container_name: $BASE_NAME-node15
    volumes:
      - data15:$DATA_DIR_IN_CONTAINER
    ports:
      - '40015:$RPC_PORT'
    depends_on:
      - node01

volumes:
  data01:
  data02:
  data03:
  data04:
  data05:
  data06:
  data07:
  data08:
  data09:
  data10:
  data11:
  data12:
  data13:
  data14:
  data15:
