[package]
name = "util"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
convert_case = "0.5"

[dependencies.syn]
version = "1.0"
features = ["full"]
