# Build Stage
FROM mintlayer-builder:latest AS builder

# Runtime Stage
FROM debian:bookworm-slim

# Install necessary runtime dependencies for the GUI (such as X11, etc.)
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/target/release/node-gui /usr/bin/node-gui

CMD ["node-gui"]
