#!/bin/sh
# postinst for mintlayer-node-gui
set -e

case "$1" in
    configure)
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q /usr/share/applications >/dev/null 2>&1 || true
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1; then
            gtk-update-icon-cache -q -f /usr/share/icons/hicolor >/dev/null 2>&1 || true
        fi
        ;;
esac

exit 0
