[package]
name = "wallet-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chainstate = { path = "../../chainstate" }
common = { path = "../../common" }
consensus = { path = "../../consensus" }
crypto = { path = "../../crypto" }
logging = { path = "../../logging" }
mempool-types = { path = "../../mempool/types" }
node-comm = { path = "../wallet-node-client" }
serialization = { path = "../../serialization" }
utils = { path = "../../utils" }
wallet = { path = ".." }
wallet-storage = { path = "../storage" }
wallet-types = { path = "../types" }

async-trait.workspace = true
bip39 = { workspace = true, default-features = false, features = ["std", "zeroize"] }
thiserror.workspace = true
tokio = { workspace = true, default-features = false, features = ["io-util", "macros", "net", "rt", "sync"] }
zeroize.workspace = true

[dev-dependencies]
chainstate-test-framework = { path = "../../chainstate/test-framework" }
test-utils = { path = "../../test-utils" }

anyhow.workspace = true
rstest.workspace = true
