[package]
name = "wallet-storage"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = '../../common' }
crypto = { path = "../../crypto" }
serialization = { path = "../../serialization" }
storage = { path = '../../storage', features = ['inmemory'] }
storage-sqlite = { path = "../../storage/sqlite" }
utxo = { path = '../../utxo' }
wallet-types = { path = '../types' }
utils = { path = '../../utils' }

thiserror.workspace = true
bip39 = { workspace = true, default-features = false, features = ["std", "zeroize"] }

[dev-dependencies]
test-utils = {path = '../../test-utils'}

rstest.workspace = true
