[package]
name = "trezor-common"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-derive.workspace = true
num-traits = { workspace = true, default-features = false, features = ["libm"] }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "chain-error"] }
strum = { workspace = true, default-features = false, features = ["derive"] }

[dev-dependencies]
test-utils = { path = "../test-utils" }
common = { path = "../common" }
crypto = { path = "../crypto" }
serialization = { path = "../serialization" }

rstest.workspace = true
trezor-client.workspace = true
