name: macOS Code Signing

on:
  push:
    branches: [ master ]

jobs:
  build-and-sign:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install the Apple certificate
      env:
        MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
        MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security import certificate.p12 -k build.keychain -P "$MACOS_CERTIFICATE_PWD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

    - name: Code Signing
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        echo "Debug: Unlocking keychain"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        
        echo "Debug: Listing codesigning identities"
        security find-identity -v -p codesigning build.keychain
        
        echo "Debug: Attempting to get certificate name"
        CERT_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Apple Distribution" | head -n 1 | sed -n 's/.*"\(.*\)"/\1/p')
        echo "Certificate name: $CERT_NAME"
        
        if [ -z "$CERT_NAME" ]; then
          echo "Error: Unable to find certificate name"
          exit 1
        fi
        
        echo "Debug: Attempting code signing"
        /usr/bin/codesign --force -s "$CERT_NAME" --options runtime --timestamp target/release/bundle/osx/Mintlayer\ Node\ GUI.app -v
        
        echo "Debug: Verifying code signature"
        /usr/bin/codesign -dv --verbose=4 target/release/bundle/osx/Mintlayer\ Node\ GUI.app

    - name: Clean up keychain
      if: ${{ always() }}
      run: security delete-keychain build.keychain