name: macOS Certificate Test (.cer format)

on:
  push:
    branches:
      - master 
jobs:
  test-macos-certificate:
    name: Test macOS Certificate
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Certificate
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "Debug: Decoding certificate"
          echo "$MACOS_CERTIFICATE" | base64 --decode > certificate.cer
          echo "Debug: Certificate decoded, checking file"
          ls -l certificate.cer
          
          echo "Debug: Creating keychain"
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          
          echo "Debug: Importing certificate"
          security import certificate.cer -k build.keychain -T /usr/bin/codesign
          
          echo "Debug: Setting key partition list"
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Verify Certificate
        run: |
          echo "Debug: Listing identities in build.keychain"
          security find-identity -v -p codesigning build.keychain
          echo "Debug: Checking certificate details"
          security find-certificate -c "Developer ID Application" -a -Z | sed -n 's/SHA-1 hash: //p' | xargs -I {} security find-certificate -Z {} -p build.keychain

      - name: Attempt Code Signing
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "Debug: Unlocking keychain"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          echo "Debug: Listing codesigning identities"
          security find-identity -v -p codesigning build.keychain
          echo "Debug: Attempting to get certificate name"
          CERT_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application" | head -n 1 | sed -n 's/.*"\(.*\)"/\1/p')
          echo "Certificate name: $CERT_NAME"
          if [ -z "$CERT_NAME" ]; then
            echo "Error: Unable to find certificate name"
            exit 1
          fi
          echo "Debug: Creating a test file for signing"
          echo "Test file" > test_file.txt
          echo "Debug: Attempting code signing"
          /usr/bin/codesign --force -s "$CERT_NAME" --keychain build.keychain test_file.txt
          echo "Debug: Verifying code signature"
          /usr/bin/codesign -dv --verbose=4 test_file.txt

      - name: Cleanup
        if: always()
        run: |
          echo "Debug: Deleting keychain"
          security delete-keychain build.keychain